version: '3.9'
services:
  prom-eu1-replica0:
    image: quay.io/prometheus/prometheus:v2.43.1
    container_name: prom-eu1-replica0
    user: root
    volumes:
      - ./data:/prometheus
      - ./prom-eu1-replica0-config.yaml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=2h
      - --storage.tsdb.min-block-duration=2h
      - --storage.tsdb.max-block-duration=2h
      - --web.listen-address=0.0.0.0:9091
      - --web.external-url=http://192.168.0.118:9091
      - --web.enable-lifecycle
      - --web.enable-admin-api
    ports:
      - 9091:9091

  prom-eu1-0-sidecar:
    image: quay.io/thanos/thanos:v0.31.0
    container_name: prom-eu1-0-sidecar
    user: root
    volumes:
      - ./data:/prometheus
      - ./prom-eu1-replica0-config.yaml:/etc/prometheus/prometheus.yml
      - ./minio-bucket.yml:/etc/thanos/minio-bucket.yml
    command:
      - sidecar
      - --tsdb.path=/prometheus
      - --objstore.config-file=/etc/thanos/minio-bucket.yml
      - --shipper.upload-compacted
      - --http-address=0.0.0.0:19091
      - --grpc-address=0.0.0.0:19191
      - --reloader.config-file=/etc/prometheus/prometheus.yml
      - --prometheus.url=http://192.168.0.118:9091
    ports:
      - 19091:19091
      - 19191:19191
