global:
  scrape_interval: 1m
  external_labels:
    cluster: eu1
    replica: 1
    tenant: team-eu

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.118:9091', '192.168.0.118:9092']