version: '3.9'
services:
  s3-minio:
    image: minio/minio:RELEASE.2023-01-20T02-05-44Z
    container_name: s3-minio
    user: root
    volumes:
      - ./data:/data
    command:
      - server
      - /data
      - --address=:9001
      - --console-address=:9991
    environment:
      - MINIO_ROOT_USER=miniodevops
      - MINIO_ROOT_PASSWORD=miniodevops
    ports:
      - 9001:9001
      - 9991:9991